### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by loic-lopez** [oanhnn/docker-laravel-echo-server#1]
Hi,

I encounter this issue : 
```bash
2018/10/14 22:01:22 unable to create open /app/laravel-echo-server.json: permission denied
```

my docker-compose file : 
```
laravel-echo-server:
    restart: ${RESTART_MODE}
    image: oanhnn/laravel-echo-server
    container_name: laravel-echo-server
    environment:
      - APP_DEBUG=true
    volumes:
      - ${STORAGE_PATH}/exosuite-laravel-echo-server:/app
    ports:
      - "6001:6001"
    networks:
      - root-network
```

Thanks for reply :)

**Comment by oanhnn** [comment]
Thank for reporting. I updated repository. Now you can try:

```
laravel-echo-server:
    restart: ${RESTART_MODE}
    image: oanhnn/laravel-echo-server:latest
    environment:
      - LARAVEL_ECHO_SERVER_DEBUG=true
    volumes:
      - ${STORAGE_PATH}/exosuite-laravel-echo-server:/app
    ports:
      - "6001:6001"
    networks:
      - root-network
```

Please reopen this issue if that still error.
