### ISSUE TITLE
echo does not receive messages

### ISSUE THREAD

**Issue by Sirgalas** [oanhnn/docker-laravel-echo-server#15]
here is docker-compose.yml
```
version: '3.6'
services:
  php-fpm:
    build: docker/php-fpm
    depends_on:
      - db
      - redis
    links:
      - redis
      - db
    volumes:
      - "./:/www"
    environment:
      - DOCKER_PHP_CONFIG=${DOCKER_PHP_CONFIG}
      - DOCKER_XDEBUG=${DOCKER_XDEBUG}
      - DOCKER_SUPERVISOR=${DOCKER_SUPERVISOR}
      - DOCKER_CRON=${DOCKER_CRON}
    networks:
        - vue

  nginx:
    image: nginx:1.16-alpine
    depends_on:
      - php-fpm
    ports:
      - "8200:80"
      - "8243:443"
    volumes:
      - "./:/www"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - vue



  redis:
    image: redis
    volumes:
      - ./docker/redis:/data
    ports:
      - "8204:6379"
    networks:
      - vue

  node:
    build: docker/nodejs
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
    depends_on:
      - php-fpm
    volumes:
      - "./:/www"
    networks:
      - vue
    ports:
      - "8205:3000"
  echo:
    image: oanhnn/laravel-echo-server:latest
    depends_on:
      - redis
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: redis
      LARAVEL_ECHO_SERVER_DEBUG: 'true'
      LARAVEL_ECHO_SERVER_DB: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    networks:
      - vue
    ports:
      - 8206:6001

networks:
  vue:
    driver: bridge
```
here is laravel-echo-server.json
```
{
    "apiOriginAllow": {},
    "authEndpoint": "/broadcasting/auth",
    "authHost": "http://localhost",
    "clients": [],
    "database": "LARAVEL_ECHO_SERVER_DB",
    "databaseConfig": {
        "redis": {
            "host": "REDIS_HOST",
            "port": "REDIS_PORT",
            "options": {
                "db": "REDIS_DB"
            }
        },
        "sqlite": {
            "databasePath": "/database/laravel-echo-server.sqlite"
        },
        "publishPresence": true
    },
    "devMode": false,
    "host": null,
    "port": 8206,
    "protocol": "http",
    "sslCertPath": "",
    "sslKeyPath": "",
    "sslCertChainPath": "",
    "sslPassphrase": "",
    "socketio": {},
    "subscribers": {"http": true, "redis": true}
}

```

so I connect it boorstrap.js 
```

window._ = require('lodash');
window.Popper= require('popper.js').default;
window.io=require('socket.io-client');


window.axios = require('axios');

window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host:window.location.hostname+':8206',
});

```
vue component

```
<template>
    <div class="container">
        <hr/>
        <div class="row">
            <div class="col-sm-12">
                <textarea class="form-control" rows="10" readonly>{{messages.join('\n')}}</textarea>
                <hr/>
                <input type="text" class="form-control" v-model="textMessage" @keyup.enter="sendMessage">
            </div>
        </div>
    </div>
</template>

<script>
export default {
    data(){
        return {
            messages:[],
            textMessage:''
        }
    },
    mounted() {
        this.addMessage('You joined the chatbox.');
        Echo.channel('chat')
            .listen('MessageEvent',({message})=>{
                this.messages.push(message);
                console.log(message);
            })
    },
    methods:{
        addMessage(message) {
            let date= new Date();
            let timestamp = date.getHours() + ':' + date.getMinutes() + ':' + date.getSeconds();
            this.messages.push(timestamp + ' ' + message);
        },
        sendMessage(){
            axios.post('chat/message',
                {
                    body:this.textMessage
                }).then((response)=>{
                    this.messages.push(response.data)
                    this.textMessage="";
                });
        }
    }
}
</script>
```
redis-cli registers the following message
```
1607282947.620026 [0 172.29.0.6:49842] "EVAL" "for i = 2, #ARGV do\n  redis.call('publish', ARGV[i], ARGV[1])\nend" "0" "{\"event\":\"App\\\\Events\\\\Chat\\\\MessageEvent\",\"data\":{\"message\":\"11\",\"socket\":null},\"socket\":null}" "chat"
1607282947.620160 [0 lua] "publish" "chat" "{\"event\":\"App\\\\Events\\\\Chat\\\\MessageEvent\",\"data\":{\"message\":\"11\",\"socket\":null},\"socket\":null}"
```
but these messages they do not come even in debug there are only messages about connecting to the client channel

```
L A R A V E L  E C H O  S E R V E R

version 1.6.2

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

[7:09:58 PM] - Qk_u__xYutZMmyqMAAAA joined channel: chat
[7:10:01 PM] - kwzT_Kk-1DVn6cQnAAAB joined channel: chat
[7:11:57 PM] - kwzT_Kk-1DVn6cQnAAAB left channel: chat (transport close)
[7:11:58 PM] - qpEoOLWSOvnU8UjaAAAC joined channel: chat
[7:12:32 PM] - Qk_u__xYutZMmyqMAAAA left channel: chat (transport close)
[7:12:33 PM] - ZSeSV4LbagHb8HieAAAD joined channel: chat
[7:12:39 PM] - ZSeSV4LbagHb8HieAAAD left channel: chat (transport close)
[7:12:40 PM] - WogY2w9Odwyh69IAAAAE joined channel: chat
[7:29:01 PM] - qpEoOLWSOvnU8UjaAAAC left channel: chat (transport close)
[7:29:03 PM] - UlNwT1oXDp9EhV00AAAG joined channel: chat
```
And it doesn't come to the browser either. What could be wrong ?
