### ISSUE TITLE
Could not subscribe to echo server channels

### ISSUE THREAD

**Issue by milkeshaa** [oanhnn/docker-laravel-echo-server#17]
Here is the docker-compose.yml 
```
version: "3.1"
services:
    laravel-echo-server:
      image: oanhnn/laravel-echo-server:2.1.1
      depends_on:
        - redis
      container_name: robocash-echo-server
      ports:
        - 6001:6001
      environment:
        REDIS_HOST: robocash-redis
        LARAVEL_ECHO_SERVER_AUTH_HOST: http://robocash-webserver
        LARAVEL_ECHO_SERVER_DEBUG: 'true'
      networks:
        - robocash

    postgres:
      image: postgres:13
      container_name: robocash-postgres
      healthcheck:
        test: pg_isready
        interval: 5s
        timeout: 10s
        retries: 120
      volumes:
        - .:/application
        - postgres-volume:/var/lib/postgresql/data
      restart: on-failure
      ports:
        - 5433:5432
      environment:
        - POSTGRES_PASSWORD=XLv1SDPvOl
        - POSTGRES_USER=robocash
        - POSTGRES_DB=robocash
      networks:
        - robocash

    webserver:
      image: nginx:alpine
      container_name: robocash-webserver
      working_dir: /application
      restart: always
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8010:80"
      networks:
        - robocash

    php-fpm:
      build: phpdocker/php-fpm
      container_name: robocash-php-fpm
      working_dir: /application
      extra_hosts:
        - "clientarea.robocash.local:172.18.0.1"
        - "admin.robocash.local:172.18.0.1"
      restart: always
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
        - robocash

    redis:
      image: redis:alpine
      container_name: robocash-redis
      ports:
        - 6380:6379
      networks:
        - robocash

volumes:
  postgres-volume:

networks:
  robocash:
    driver: bridge
```
Using auto-generated by yours container laravel-echo-server.json file.
Connecting as:
```
  window.Echo = new Echo({
          broadcaster: 'socket.io',
          host: window.location.hostname + ':' + '{{ env('SOCKET_PORT') }}'
      });
      window.Echo.channel('news').listen('NewsCreated', (e) => {
          console.log(e);
      });
```
    
But see nothing about success subscription on channel 'news' in logs:
![image](https://user-images.githubusercontent.com/42216731/107605038-08223400-6c43-11eb-8993-4db1bd4b3ceb.png)
    
But when invoking event, it appears in logs:
![image](https://user-images.githubusercontent.com/42216731/107605116-4cadcf80-6c43-11eb-9cb6-dcfaf0495c95.png)

No errors in browser console. Seems like i have connection with sockets:
![image](https://user-images.githubusercontent.com/42216731/107605174-6f3fe880-6c43-11eb-8638-c07d3e34ae78.png)

So, event comes to server but as i cannot subscribe to channels i cannot receive that events in browser. Could you tell me, where am i wrong?
