### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80 on Laravel Sail

### ISSUE THREAD

**Issue by SidneySaints** [oanhnn/docker-laravel-echo-server#22]
I try to implement docker-laravel-echo-server into Laravel Sail
```jml version: '3'
services:
    app:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                XDEBUG: ${APP_DEBUG}
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        extra_hosts:
          - "host.docker.internal:host-gateway"
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - selenium
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
       image: 'selenium/standalone-chrome'
       volumes:
            - '/dev/shm:/dev/shm'
       networks:
           - sail
    laravel-echo-server:
      image: oanhnn/laravel-echo-server
      depends_on:
        - redis
      ports:
        - 6001:6001
      environment:
        LARAVEL_ECHO_SERVER_DEBUG: 'true'
      networks:
        - sail

networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local
```
Joining of public channels works fine, but if i want to join a private channel i get these error
```bash
laravel-echo-server_1  | [12:00:07 PM] - Error authenticating ScG5vjw0NJ4rNjkgAAAA for private-notify
laravel-echo-server_1  | Error: connect ECONNREFUSED 127.0.0.1:80
laravel-echo-server_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
laravel-echo-server_1  |   errno: -111,
laravel-echo-server_1  |   code: 'ECONNREFUSED',
laravel-echo-server_1  |   syscall: 'connect',
laravel-echo-server_1  |   address: '127.0.0.1',
laravel-echo-server_1  |   port: 80
laravel-echo-server_1  | }
```

**Comment by SidneySaints** [comment]
I got a solution.. :-)
for everyone who faces the same problem.. just use the example config..
```yml
laravel-echo-server:
      image: oanhnn/laravel-echo-server:latest
      depends_on:
        - redis
      environment:
        LARAVEL_ECHO_SERVER_AUTH_HOST: http://[replace_this_with_app_container_name]
        LARAVEL_ECHO_SERVER_DEBUG: 'true'
        LARAVEL_ECHO_SERVER_DB: redis
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_PREFIX: null
        REDIS_PASSWORD: null
        REDIS_DB: 0
      networks:
        - sail
      ports:
        - 6001:6001
      restart: unless-stopped
      healthcheck:
        test: node /usr/local/src/healthcheck.js
        start_period: 5s
        interval: 3s
        timeout: 3s
        retries: 10
```
