### ISSUE TITLE
ERR_EMPTY_RESPONSE with connection

### ISSUE THREAD

**Issue by Troodi** [oanhnn/docker-laravel-echo-server#23]
`http://localhost:6001/socket.io/?EIO=3&transport=polling&t=NkUj6jL` link from network tab.

My config:
```
{
	"authHost": "http://localhost:8844",
	"authEndpoint": "http://localhost:8844/broadcasting/auth",
	"clients": [
		{
			"appId": "***",
			"key": "***"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
		  "port": "6379",
		  "host": "redis",
		  "keyPrefix": "laravel_database_"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "127.0.0.1",
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"secureOptions": 67108864,
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"subscribers": {
		"http": true,
		"redis": true
	},
	"apiOriginAllow": {
		"allowCors": true,
		"allowOrigin": "http://localhost::8844",
		"allowMethods": "GET, POST",
		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	}
}
```

And my docker compose config:

```
# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.0-fpm-alpine3.14
    container_name: app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./php/conf.d:/usr/local/etc/php/conf.d/
  db:
    image: mysql:8.0.26
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_DATABASE: example
      MYSQL_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql/
      - ./mysql:/etc/mysql/
      - ./mysql-files:/var/lib/mysql-files
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
  redis:
    image: redis:alpine3.14
    container_name: redis
    restart: always
    volumes:
      - ./redis:/usr/local/etc/redis/
    ports:
      - 6379:6379
  echoserver:
    image: oanhnn/laravel-echo-server:latest
    container_name: laravel-echo-server
    restart: always
    ports:
      - 6001:6001
    volumes:
      - ./laravel-echo-server:/app
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8844:80
      - 4433:443
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
volumes: 
    dbdata:
        driver: local
```

How to fix it?
